/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Adult: typeof import('./src/components/adult.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sign: typeof import('./src/components/sign.vue')['default']
    Solar: typeof import('./src/components/solar.vue')['default']
    VarBackTop: typeof import('@varlet/ui')['_BackTopComponent']
    VarCol: typeof import('@varlet/ui')['_ColComponent']
    VarImage: typeof import('@varlet/ui')['_ImageComponent']
    VarRow: typeof import('@varlet/ui')['_RowComponent']
  }
}
